import json, re, unicodedata, pathlib
base=pathlib.Path('/mnt/data/euro-champions-draft')

def slug(s):
    s=unicodedata.normalize('NFKD',s).encode('ascii','ignore').decode().lower()
    return re.sub(r'[^a-z0-9]+','_',s).strip('_')

def P(name,pos,rating,traits=None):
    return dict(name=name,positions=pos if isinstance(pos,list) else [pos],rating=rating,traits=traits or [])

raw=[
('barca_2014_15','Barcelona','2014/15','Winner','MSN Treble',[
P('Marc-André ter Stegen','GK',90,['Shot Stopper']),P('Claudio Bravo','GK',88,['Sweeper Keeper']),P('Dani Alves','RB',90,['Creator']),P('Gerard Piqué','CB',91,['Aerial']),P('Javier Mascherano',['CB','CDM'],89,['Warrior']),P('Jordi Alba','LB',90,['Overlap']),P('Sergio Busquets',['CDM','CM'],93,['Press Resistant']),P('Xavi','CM',91,['Controller']),P('Andrés Iniesta',['CM','CAM'],94,['Magician']),P('Ivan Rakitić',['CM','RM'],90,['Engine']),P('Lionel Messi',['RW','CAM','ST'],99,['UCL Legend','Clutch','Ballon d’Or']),P('Luis Suárez','ST',96,['Killer','Big Game']),P('Neymar',['LW','CAM'],94,['Flair','Big Game']),P('Pedro',['RW','LW'],86,['Utility'])]),
('real_2016_17','Real Madrid','2016/17','Winner','La Duodécima',[
P('Keylor Navas','GK',90,['Shot Stopper']),P('Dani Carvajal','RB',90,['Overlap']),P('Sergio Ramos','CB',94,['Captain','Clutch','Aerial']),P('Raphaël Varane','CB',90,['Recovery Pace']),P('Marcelo','LB',93,['Creator','Flair']),P('Casemiro','CDM',91,['Ball Winner']),P('Toni Kroos','CM',94,['Controller']),P('Luka Modrić','CM',94,['Press Resistant']),P('Isco',['CAM','CM'],91,['Magician']),P('Gareth Bale',['RW','LW'],92,['Pace']),P('Karim Benzema','ST',92,['Link-up']),P('Cristiano Ronaldo',['LW','ST'],98,['UCL Legend','Clutch','Big Game','Ballon d’Or']),P('Álvaro Morata','ST',86,['Super Sub']),P('Marco Asensio',['LW','RW','CAM'],86,['Young Gun'])]),
('bayern_2012_13','Bayern Munich','2012/13','Winner','Treble Machine',[
P('Manuel Neuer','GK',94,['Sweeper Keeper','Big Game']),P('Philipp Lahm',['RB','LB','CDM'],94,['Captain','Controller']),P('Dante','CB',89,['Aerial']),P('Jérôme Boateng','CB',90,['Recovery Pace']),P('David Alaba',['LB','CM'],91,['Overlap']),P('Javi Martínez',['CDM','CB'],91,['Ball Winner']),P('Bastian Schweinsteiger','CM',93,['Leader','Big Game']),P('Toni Kroos',['CM','CAM'],90,['Controller']),P('Thomas Müller',['CAM','ST','RW'],91,['Raumdeuter','Big Game']),P('Franck Ribéry','LW',94,['Flair']),P('Arjen Robben','RW',94,['Clutch','Big Game']),P('Mario Mandžukić','ST',90,['Target Man']),P('Luiz Gustavo','CDM',86,['Destroyer'])]),
('inter_2009_10','Inter Milan','2009/10','Winner','Mourinho Treble',[
P('Júlio César','GK',93,['Shot Stopper']),P('Maicon','RB',92,['Overlap']),P('Lúcio','CB',92,['Warrior']),P('Walter Samuel','CB',91,['Aerial']),P('Cristian Chivu',['LB','CB'],86,['Utility']),P('Javier Zanetti',['LB','RB','CM'],91,['Captain','Mentality']),P('Esteban Cambiasso','CDM',91,['Ball Winner']),P('Thiago Motta','CM',88,['Controller']),P('Wesley Sneijder','CAM',94,['Playmaker','Big Game']),P('Samuel Eto’o',['LW','ST'],92,['Big Game']),P('Diego Milito','ST',93,['Clutch','Killer']),P('Goran Pandev',['RW','ST'],86,['Worker']),P('Dejan Stanković',['CM','CAM'],88,['Long Shot'])]),
('liverpool_2018_19','Liverpool','2018/19','Winner','Mentality Monsters',[
P('Alisson Becker','GK',93,['Shot Stopper']),P('Trent Alexander-Arnold','RB',90,['Creator']),P('Virgil van Dijk','CB',96,['Defensive Wall','Aerial']),P('Joël Matip','CB',88,['Aerial']),P('Andrew Robertson','LB',90,['Overlap']),P('Fabinho','CDM',90,['Ball Winner']),P('Jordan Henderson','CM',87,['Captain','Engine']),P('Georginio Wijnaldum','CM',88,['Big Game']),P('James Milner',['CM','LB'],86,['Utility']),P('Mohamed Salah','RW',93,['Killer']),P('Sadio Mané','LW',92,['Press Monster']),P('Roberto Firmino','ST',90,['Link-up']),P('Divock Origi','ST',84,['Clutch'])]),
('chelsea_2011_12','Chelsea','2011/12','Winner','Munich Miracle',[
P('Petr Čech','GK',93,['Shot Stopper','Big Game']),P('Branislav Ivanović',['RB','CB'],89,['Aerial']),P('David Luiz','CB',88,['Ball Playing CB']),P('Gary Cahill','CB',87,['Aerial']),P('Ashley Cole','LB',91,['Defensive Wall']),P('John Terry','CB',91,['Captain']),P('John Obi Mikel','CDM',87,['Ball Winner']),P('Frank Lampard','CM',91,['Leader','Big Game']),P('Ramires',['CM','RM'],88,['Engine']),P('Juan Mata',['CAM','RW'],89,['Playmaker']),P('Florent Malouda',['LW','LM'],85,['Worker']),P('Didier Drogba','ST',92,['Clutch','Big Game']),P('Fernando Torres','ST',86,['Pace'])]),
('milan_2006_07','AC Milan','2006/07','Winner','Athens Revenge',[
P('Dida','GK',89,['Shot Stopper']),P('Cafu','RB',89,['Overlap']),P('Alessandro Nesta','CB',94,['Defensive Wall']),P('Paolo Maldini',['CB','LB'],94,['Captain','Mentality']),P('Marek Jankulovski','LB',87,['Overlap']),P('Gennaro Gattuso','CDM',91,['Warrior']),P('Andrea Pirlo','CM',94,['Controller']),P('Massimo Ambrosini','CM',88,['Aerial']),P('Clarence Seedorf',['CAM','CM'],92,['Big Game']),P('Kaká','CAM',97,['Ballon d’Or','Clutch','Big Game']),P('Filippo Inzaghi','ST',91,['Killer','Clutch']),P('Alberto Gilardino','ST',87,['Finisher'])]),
('united_2007_08','Manchester United','2007/08','Winner','Moscow Kings',[
P('Edwin van der Sar','GK',92,['Shot Stopper']),P('Wes Brown','RB',86,['Utility']),P('Rio Ferdinand','CB',94,['Defensive Wall']),P('Nemanja Vidić','CB',93,['Aerial','Warrior']),P('Patrice Evra','LB',90,['Overlap']),P('Michael Carrick','CM',89,['Controller']),P('Paul Scholes','CM',90,['Playmaker']),P('Owen Hargreaves',['CM','RB'],87,['Engine']),P('Ryan Giggs',['LM','CM'],88,['Experience']),P('Cristiano Ronaldo',['LW','RW','ST'],98,['Ballon d’Or','UCL Legend','Big Game']),P('Wayne Rooney',['ST','LW'],92,['Worker','Big Game']),P('Carlos Tévez','ST',90,['Press Monster']),P('Nani',['RW','LW'],86,['Flair'])]),
('city_2022_23','Manchester City','2022/23','Winner','Treble Control',[
P('Ederson','GK',91,['Sweeper Keeper']),P('Kyle Walker','RB',89,['Recovery Pace']),P('Rúben Dias','CB',92,['Defensive Wall']),P('John Stones',['CB','CDM'],90,['Ball Playing CB']),P('Nathan Aké',['LB','CB'],88,['Utility']),P('Manuel Akanji',['CB','RB','LB'],88,['Utility']),P('Rodri','CDM',94,['Controller','Big Game']),P('İlkay Gündoğan','CM',91,['Captain','Clutch']),P('Kevin De Bruyne',['CM','CAM'],95,['Playmaker','Big Game']),P('Bernardo Silva',['RW','CM'],92,['Press Resistant']),P('Jack Grealish','LW',88,['Ball Carrier']),P('Riyad Mahrez','RW',88,['Flair']),P('Erling Haaland','ST',95,['Killer'])]),
('dortmund_2012_13','Borussia Dortmund','2012/13','Finalist','Yellow Wall Run',[
P('Roman Weidenfeller','GK',89,['Shot Stopper']),P('Łukasz Piszczek','RB',89,['Overlap']),P('Mats Hummels','CB',91,['Ball Playing CB']),P('Neven Subotić','CB',88,['Aerial']),P('Marcel Schmelzer','LB',86,['Overlap']),P('Sven Bender','CDM',87,['Ball Winner']),P('İlkay Gündoğan','CM',91,['Controller']),P('Sebastian Kehl','CDM',85,['Leader']),P('Jakub Błaszczykowski','RW',88,['Worker']),P('Mario Götze',['CAM','LW'],90,['Playmaker']),P('Marco Reus',['LW','CAM'],91,['Flair']),P('Kevin Großkreutz',['LM','RM','LB'],86,['Utility']),P('Robert Lewandowski','ST',94,['Killer','Big Game'])]),
# expansion
('porto_2003_04','Porto','2003/04','Winner','Mourinho Underdogs',[
P('Vítor Baía','GK',88,['Shot Stopper']),P('Paulo Ferreira','RB',88,['Defensive Fullback']),P('Jorge Costa','CB',88,['Captain']),P('Ricardo Carvalho','CB',92,['Defensive Wall']),P('Nuno Valente','LB',87,['Overlap']),P('Costinha','CDM',88,['Ball Winner']),P('Maniche','CM',90,['Engine','Big Game']),P('Deco','CAM',93,['Playmaker','Big Game']),P('Pedro Mendes','CM',86,['Controller']),P('Carlos Alberto',['CAM','RW'],87,['Clutch']),P('Derlei','ST',88,['Killer']),P('Benni McCarthy','ST',87,['Finisher'])]),
('ajax_2018_19','Ajax','2018/19','Semi-finalist','Young Chaos',[
P('André Onana','GK',88,['Sweeper Keeper']),P('Noussair Mazraoui','RB',86,['Overlap']),P('Matthijs de Ligt','CB',91,['Captain','Aerial']),P('Daley Blind',['CB','CDM'],88,['Controller']),P('Nicolás Tagliafico','LB',87,['Overlap']),P('Frenkie de Jong','CM',92,['Press Resistant']),P('Lasse Schöne','CM',86,['Controller']),P('Donny van de Beek',['CAM','CM'],88,['Engine']),P('Hakim Ziyech',['RW','CAM'],90,['Creator']),P('Dušan Tadić',['ST','LW'],90,['False 9']),P('David Neres',['LW','RW'],88,['Flair']),P('Kasper Dolberg','ST',84,['Finisher'])]),
('juve_2016_17','Juventus','2016/17','Finalist','BBC Wall',[
P('Gianluigi Buffon','GK',94,['UCL Legend','Shot Stopper']),P('Dani Alves',['RB','RM'],90,['Creator','Big Game']),P('Leonardo Bonucci','CB',92,['Ball Playing CB']),P('Giorgio Chiellini','CB',93,['Warrior']),P('Andrea Barzagli','CB',90,['Defensive Wall']),P('Alex Sandro','LB',90,['Overlap']),P('Miralem Pjanić','CM',89,['Controller']),P('Sami Khedira','CM',87,['Engine']),P('Claudio Marchisio','CM',87,['Controller']),P('Paulo Dybala',['CAM','ST'],91,['Flair']),P('Mario Mandžukić',['LW','ST'],89,['Worker']),P('Gonzalo Higuaín','ST',91,['Killer'])]),
('atleti_2015_16','Atlético Madrid','2015/16','Finalist','Cholo Block',[
P('Jan Oblak','GK',92,['Shot Stopper']),P('Juanfran','RB',87,['Overlap']),P('Diego Godín','CB',92,['Defensive Wall','Aerial']),P('José María Giménez','CB',88,['Aerial']),P('Filipe Luís','LB',89,['Overlap']),P('Gabi','CM',88,['Captain','Ball Winner']),P('Koke',['CM','RM'],90,['Playmaker']),P('Saúl Ñíguez','CM',88,['Engine']),P('Yannick Carrasco',['LW','RW'],87,['Pace']),P('Antoine Griezmann',['ST','CAM'],92,['Killer','Big Game']),P('Fernando Torres','ST',86,['Experience']),P('Ángel Correa',['RW','ST'],84,['Flair'])]),
('psg_2019_20','PSG','2019/20','Finalist','Lisbon Bubble',[
P('Keylor Navas','GK',90,['Shot Stopper','Big Game']),P('Thilo Kehrer',['RB','CB'],84,['Utility']),P('Marquinhos',['CB','CDM'],91,['Leader']),P('Presnel Kimpembe','CB',87,['Aerial']),P('Juan Bernat','LB',86,['Overlap']),P('Leandro Paredes','CM',86,['Controller']),P('Marco Verratti','CM',90,['Press Resistant']),P('Ángel Di María',['RW','CM'],90,['Creator','Big Game']),P('Neymar',['LW','CAM'],94,['Flair','Big Game']),P('Kylian Mbappé',['ST','RW','LW'],93,['Pace','Killer']),P('Mauro Icardi','ST',86,['Finisher']),P('Pablo Sarabia',['RW','CAM'],84,['Utility'])]),
('tottenham_2018_19','Tottenham Hotspur','2018/19','Finalist','Miracle Run',[
P('Hugo Lloris','GK',89,['Shot Stopper']),P('Kieran Trippier','RB',86,['Creator']),P('Toby Alderweireld','CB',89,['Ball Playing CB']),P('Jan Vertonghen',['CB','LB'],89,['Defensive Wall']),P('Danny Rose','LB',85,['Overlap']),P('Moussa Sissoko','CM',86,['Engine']),P('Harry Winks','CM',84,['Controller']),P('Dele Alli',['CAM','CM'],87,['Box Crasher']),P('Christian Eriksen',['CAM','CM'],90,['Playmaker']),P('Lucas Moura',['RW','ST'],88,['Clutch','Pace']),P('Son Heung-min',['LW','ST'],90,['Killer']),P('Harry Kane','ST',92,['Killer','Big Game'])]),
('monaco_2016_17','Monaco','2016/17','Semi-finalist','Mbappé Breakout',[
P('Danijel Subašić','GK',87,['Shot Stopper']),P('Djibril Sidibé','RB',86,['Overlap']),P('Kamil Glik','CB',87,['Aerial']),P('Jemerson','CB',85,['Defensive Wall']),P('Benjamin Mendy','LB',87,['Overlap']),P('Fabinho','CDM',89,['Ball Winner']),P('Tiémoué Bakayoko','CM',87,['Engine']),P('João Moutinho','CM',87,['Controller']),P('Thomas Lemar',['LM','LW'],88,['Creator']),P('Bernardo Silva',['RW','CAM'],90,['Magician']),P('Kylian Mbappé',['ST','RW'],90,['Pace','Killer']),P('Radamel Falcao','ST',89,['Killer'])]),
('roma_2017_18','Roma','2017/18','Semi-finalist','Remontada Energy',[
P('Alisson Becker','GK',91,['Shot Stopper']),P('Alessandro Florenzi',['RB','RM'],86,['Utility']),P('Kostas Manolas','CB',88,['Aerial','Clutch']),P('Federico Fazio','CB',86,['Aerial']),P('Aleksandar Kolarov','LB',87,['Set Pieces']),P('Daniele De Rossi','CDM',88,['Leader','Ball Winner']),P('Kevin Strootman','CM',86,['Engine']),P('Radja Nainggolan','CM',88,['Warrior']),P('Lorenzo Pellegrini','CM',84,['Young Gun']),P('Cengiz Ünder','RW',84,['Flair']),P('Diego Perotti','LW',85,['Creator']),P('Edin Džeko','ST',89,['Killer'])]),
('lyon_2019_20','Lyon','2019/20','Semi-finalist','Upset Merchants',[
P('Anthony Lopes','GK',87,['Shot Stopper']),P('Léo Dubois','RB',84,['Overlap']),P('Marcelo','CB',84,['Aerial']),P('Jason Denayer','CB',85,['Recovery Pace']),P('Fernando Marçal','LB',83,['Utility']),P('Bruno Guimarães','CM',86,['Controller']),P('Houssem Aouar','CM',88,['Magician']),P('Maxence Caqueret','CM',84,['Press Resistant']),P('Memphis Depay',['ST','LW'],89,['Flair']),P('Karl Toko Ekambi',['LW','ST'],84,['Pace']),P('Moussa Dembélé','ST',86,['Killer']),P('Bertrand Traoré','RW',83,['Flair'])]),
('villarreal_2021_22','Villarreal','2021/22','Semi-finalist','Emery Knockout Ball',[
P('Gerónimo Rulli','GK',85,['Shot Stopper']),P('Juan Foyth',['RB','CB'],85,['Defensive Fullback']),P('Raúl Albiol','CB',86,['Leader']),P('Pau Torres','CB',88,['Ball Playing CB']),P('Pervis Estupiñán','LB',85,['Overlap']),P('Étienne Capoue','CM',86,['Ball Winner']),P('Dani Parejo','CM',88,['Controller']),P('Francis Coquelin','CM',84,['Destroyer']),P('Giovani Lo Celso',['CAM','RW'],86,['Creator']),P('Arnaut Danjuma',['LW','ST'],87,['Killer']),P('Gerard Moreno','ST',88,['Killer']),P('Samuel Chukwueze','RW',84,['Pace'])]),
('napoli_2022_23','Napoli','2022/23','Quarter-finalist','Spalletti Ball',[
P('Alex Meret','GK',86,['Shot Stopper']),P('Giovanni Di Lorenzo','RB',88,['Captain','Overlap']),P('Kim Min-jae','CB',90,['Defensive Wall']),P('Amir Rrahmani','CB',86,['Aerial']),P('Mário Rui','LB',84,['Overlap']),P('Stanislav Lobotka','CDM',88,['Controller']),P('André-Frank Zambo Anguissa','CM',87,['Engine']),P('Piotr Zieliński','CM',87,['Creator']),P('Hirving Lozano','RW',85,['Pace']),P('Khvicha Kvaratskhelia','LW',90,['Flair']),P('Victor Osimhen','ST',91,['Killer']),P('Giacomo Raspadori',['ST','CAM'],84,['Utility'])]),
('arsenal_2005_06','Arsenal','2005/06','Finalist','Highbury Farewell',[
P('Jens Lehmann','GK',89,['Shot Stopper']),P('Emmanuel Eboué','RB',85,['Overlap']),P('Kolo Touré','CB',89,['Recovery Pace']),P('Philippe Senderos','CB',84,['Aerial']),P('Ashley Cole','LB',90,['Overlap']),P('Gilberto Silva','CDM',88,['Ball Winner']),P('Cesc Fàbregas','CM',88,['Playmaker']),P('Robert Pirès','LM',88,['Creator']),P('Freddie Ljungberg','RM',87,['Box Crasher']),P('Alexander Hleb',['RM','CAM'],86,['Dribbler']),P('Dennis Bergkamp',['ST','CAM'],88,['Playmaker']),P('Thierry Henry','ST',96,['UCL Legend','Killer','Big Game'])]),
('valencia_2000_01','Valencia','2000/01','Finalist','Cúper Machine',[
P('Santiago Cañizares','GK',91,['Shot Stopper']),P('Jocelyn Angloma','RB',86,['Defensive Fullback']),P('Mauricio Pellegrino','CB',87,['Aerial']),P('Roberto Ayala','CB',91,['Defensive Wall']),P('Amedeo Carboni','LB',87,['Experience']),P('David Albelda','CDM',88,['Ball Winner']),P('Gaizka Mendieta','CM',92,['Playmaker','Big Game']),P('Rubén Baraja','CM',89,['Engine']),P('Kily González','LM',88,['Creator']),P('Pablo Aimar','CAM',89,['Magician']),P('John Carew','ST',87,['Target Man']),P('Juan Sánchez','ST',86,['Finisher'])]),
('leverkusen_2001_02','Bayer Leverkusen','2001/02','Finalist','Neverkusen Magic',[
P('Hans-Jörg Butt','GK',88,['Penalty Taker']),P('Zoltán Sebescen','RB',84,['Utility']),P('Lúcio','CB',91,['Ball Playing CB']),P('Jens Nowotny','CB',88,['Leader']),P('Diego Placente','LB',86,['Overlap']),P('Carsten Ramelow','CDM',87,['Ball Winner']),P('Bernd Schneider','RM',89,['Creator']),P('Michael Ballack','CM',93,['Big Game','Box Crasher']),P('Zé Roberto','LM',90,['Flair']),P('Oliver Neuville','ST',88,['Killer']),P('Dimitar Berbatov','ST',87,['Link-up']),P('Yıldıray Baştürk','CAM',88,['Playmaker'])]),
('chelsea_2020_21','Chelsea','2020/21','Winner','Tuchel Lockdown',[
P('Édouard Mendy','GK',91,['Shot Stopper']),P('Reece James',['RB','RWB'],88,['Overlap']),P('Thiago Silva','CB',90,['Leader']),P('Antonio Rüdiger','CB',89,['Warrior']),P('César Azpilicueta',['CB','RB'],88,['Captain']),P('Ben Chilwell',['LB','LWB'],87,['Overlap']),P('N’Golo Kanté','CM',94,['Ball Winner','Big Game']),P('Jorginho','CM',89,['Controller']),P('Mason Mount',['CAM','CM'],88,['Engine']),P('Kai Havertz',['ST','CAM'],88,['Clutch']),P('Timo Werner',['ST','LW'],86,['Pace']),P('Christian Pulisic',['LW','RW'],86,['Pace'])]),
('real_2021_22','Real Madrid','2021/22','Winner','Comeback Kings',[
P('Thibaut Courtois','GK',94,['Shot Stopper','Big Game']),P('Dani Carvajal','RB',88,['Overlap']),P('Éder Militão','CB',89,['Recovery Pace']),P('David Alaba',['CB','LB'],90,['Leader']),P('Ferland Mendy','LB',87,['Defensive Fullback']),P('Casemiro','CDM',90,['Ball Winner']),P('Toni Kroos','CM',91,['Controller']),P('Luka Modrić','CM',93,['Press Resistant','Big Game']),P('Federico Valverde',['CM','RW'],89,['Engine']),P('Vinícius Júnior','LW',92,['Pace','Clutch']),P('Karim Benzema','ST',97,['Ballon d’Or','Clutch','Big Game']),P('Rodrygo',['RW','LW'],87,['Clutch'])]),
('bayern_2019_20','Bayern Munich','2019/20','Winner','Flick Machine',[
P('Manuel Neuer','GK',93,['Sweeper Keeper','Big Game']),P('Joshua Kimmich',['RB','CDM','CM'],92,['Controller']),P('Jérôme Boateng','CB',87,['Ball Playing CB']),P('David Alaba',['CB','LB'],89,['Ball Playing CB']),P('Alphonso Davies','LB',90,['Pace']),P('Thiago Alcântara','CM',92,['Press Resistant']),P('Leon Goretzka','CM',89,['Engine']),P('Thomas Müller',['CAM','ST'],91,['Raumdeuter']),P('Serge Gnabry',['RW','LW'],90,['Killer']),P('Kingsley Coman',['LW','RW'],89,['Clutch']),P('Ivan Perišić',['LW','LM'],86,['Worker']),P('Robert Lewandowski','ST',97,['Killer','Big Game'])]),
('real_2013_14','Real Madrid','2013/14','Winner','La Décima',[
P('Iker Casillas','GK',91,['UCL Legend','Shot Stopper']),P('Dani Carvajal','RB',87,['Overlap']),P('Pepe','CB',90,['Warrior']),P('Sergio Ramos','CB',93,['Captain','Clutch']),P('Fábio Coentrão','LB',86,['Defensive Fullback']),P('Xabi Alonso','CDM',91,['Controller']),P('Luka Modrić','CM',91,['Press Resistant']),P('Ángel Di María',['CM','RW'],92,['Engine','Big Game']),P('Gareth Bale',['RW','LW'],92,['Pace','Clutch']),P('Karim Benzema','ST',91,['Link-up']),P('Cristiano Ronaldo',['LW','ST'],98,['UCL Legend','Ballon d’Or','Big Game']),P('Isco',['CAM','CM'],88,['Magician'])])
]
seasons=[]; players=[]
for sid,club,season,result,theme,plist in raw:
    seasons.append(dict(id=sid,club=club,season=season,result=result,theme=theme))
    for p in plist:
        d={
          'id': f"{sid}_{slug(p['name'])}",
          'name':p['name'],'club':club,'season':season,'seasonId':sid,
          'positions':p['positions'],'rating':p['rating'],'traits':p['traits']}
        players.append(d)
# de-dupe in same id? add suffix if necessary
seen={}
for p in players:
    if p['id'] in seen:
        seen[p['id']]+=1; p['id']=p['id']+'_'+str(seen[p['id']])
    else: seen[p['id']]=1
(base/'src/data/seasons.js').write_text('export const seasons = '+json.dumps(seasons,ensure_ascii=False,indent=2)+';\n')
(base/'src/data/players.js').write_text('export const players = '+json.dumps(players,ensure_ascii=False,indent=2)+';\n')
print(len(seasons),len(players))
